spring:
  datasource:
    url: jdbc:mysql://192.168.0.148:3306/websocketchat?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: webSocketChat
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    org:
      hibernate: info

